#!/bin/bash

i=0
while IFS=: read -r username password uid gid gecos homedir shell; do
    echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. $i's place is protected by the passcode $password, more info about the user here: $gecos"
    i=$((i+1))
done < /etc/passwd
