#!/usr/bin/env bash
# This script prints "To infinity and beyond" every 2 seconds indefinitely

while true; do
  echo "To infinity and beyond"
  sleep 2

  # If stop file exists, exit
  if [ -e /tmp/stop_infinity ]; then
    rm -f /tmp/stop_infinity
    break
  fi
done
